# Generated by Django 5.1.4 on 2026-03-22 22:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MealPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('week_start', models.DateField()),
            ],
            options={
                'db_table': 'meal_plans',
                'ordering': ['-week_start'],
            },
        ),
        migrations.CreateModel(
            name='MealPlanEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.IntegerField(choices=[(0, 0), (1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6)], help_text='0 = Monday, 6 = Sunday')),
                ('meal_type', models.CharField(choices=[('breakfast', 'Breakfast'), ('lunch', 'Lunch'), ('dinner', 'Dinner'), ('snack', 'Snack')], max_length=10)),
                ('servings', models.DecimalField(decimal_places=2, max_digits=5)),
            ],
            options={
                'db_table': 'meal_plan_entries',
                'ordering': ['day', 'meal_type'],
            },
        ),
    ]
