# Generated by Django 5.1.4 on 2026-03-22 22:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('meal_plans', '0001_initial'),
        ('recipes', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='mealplan',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meal_plans', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='mealplanentry',
            name='meal_plan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='meal_plans.mealplan'),
        ),
        migrations.AddField(
            model_name='mealplanentry',
            name='recipe',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meal_plan_entries', to='recipes.recipe'),
        ),
        migrations.AlterUniqueTogether(
            name='mealplan',
            unique_together={('user', 'week_start')},
        ),
    ]
