# Generated by Django 5.1.4 on 2026-03-23 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0004_recipeingredient_unit_maxlength'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='model_name',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
