# Generated by Django 5.1.4 on 2026-03-22 22:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('category', models.CharField(choices=[('protein', 'Protein'), ('carb', 'Carbohydrate'), ('vegetable', 'Vegetable'), ('dairy', 'Dairy'), ('spice', 'Spice'), ('other', 'Other')], default='other', max_length=20)),
                ('default_unit', models.CharField(choices=[('g', 'Grams'), ('ml', 'Millilitres'), ('cup', 'Cup'), ('tsp', 'Teaspoon'), ('tbsp', 'Tablespoon'), ('piece', 'Piece')], default='g', max_length=10)),
                ('calories_per_100g', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True)),
                ('protein_g', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True)),
                ('carbs_g', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True)),
                ('fat_g', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True)),
            ],
            options={
                'verbose_name': 'Ingredient',
                'verbose_name_plural': 'Ingredients',
                'db_table': 'ingredients',
                'ordering': ['name'],
            },
        ),
    ]
